title: isak jones
email: isak.jones.980@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website. I use it to illustrate my journey into programming
  and share my latest thoughts on topics including software engineering,
  philosophy, politics, food, and whatever else I'm currently obsessed with.

url: "https://isomorphicdude.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: isak_jones
github_username: sekerez

# Build settings
remote_theme: zivong/ockham
plugins:
  - jekyll-feed












# title: Isomorphicdude's Blog
# email: your-email@example.com

# #baseurl: "/_posts" # the subpath of your site, e.g. /blog "_posts"
# url: " https://isomorphicdude.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# github_username:  isomorphicdude


# markdown: kramdown
# # Build settings
# plugins:
#   - jekyll-remote-theme
  
# plugins:
#   - jekyll-feed
  
# remote_theme: zivong/ockham

# # markdown: kramdown
# # kramdown:
# #   input: GFM
# #   hard_wrap: false
# #   math_engine: mathjax
# #   syntax_highlighter: rouge
# # Exclude from processing.
# # The following items will not be processed, by default.
# # Any item listed under the `exclude:` key here will be automatically added to
# # the internal "default list".
# #
# # Excluded items can be processed by explicitly listing the directories or
# # their entries' file path in the `include:` list.
# #
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - CNAME
# # exclude:
# #   - .sass-cache/
# #   - .jekyll-cache/
# #   - gemfiles/
# #   - Gemfile
# #   - Gemfile.lock
# #   - node_modules/
# #   - vendor/bundle/
# #   - vendor/cache/
# #   - vendor/gems/
# #   - vendor/ruby/
