title: Almost Surely There
tagline: "@isomorphicdude"
description: Feel free to leave a comment
author.name: isomorphicdude
lang: en-us
plugins:
  - jekyll-remote-theme
remote_theme: zivong/jekyll-theme-hydure
include:  
  - _pages