title: Isomorphicdude's Blog
email: your-email@example.com

#baseurl: "/_posts" # the subpath of your site, e.g. /blog "_posts"
url: " https://isomorphicdude.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  isomorphicdude

# Build settings
# plugins:
#   - jekyll-remote-theme
  
plugins:
  - jekyll-feed
  
# remote_theme: zivong/ockham
markdown: kramdown
# markdown: kramdown
# kramdown:
#   input: GFM
#   hard_wrap: false
#   math_engine: mathjax
#   syntax_highlighter: rouge
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
